name: sap

on:
  push:
    branches:
      - testing-snap
  pull_request:
    branches:
      - testing-snap

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["7", "11", "21"]
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
          distribution: 'sapmachine' 
          java-version: ${{ matrix.java-version }}
